// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3kWHk7R2dcclIwWQBbRohYjnRiY1PHYs',
    appId: '1:1072582012438:web:455fff48076143d5180f37',
    messagingSenderId: '1072582012438',
    projectId: 'smartclass-ef1bf',
    authDomain: 'smartclass-ef1bf.firebaseapp.com',
    storageBucket: 'smartclass-ef1bf.firebasestorage.app',
    measurementId: 'G-CQ8EF7JZ9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAil6a54Y20Cd4UhEnfF7d7I5vbqNZcAVg',
    appId: '1:1072582012438:android:f09387d74398be66180f37',
    messagingSenderId: '1072582012438',
    projectId: 'smartclass-ef1bf',
    storageBucket: 'smartclass-ef1bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPkfOzLnObH9b4P8UsrkTkk0qI-0yG3g',
    appId: '1:1072582012438:ios:cd8601fa15128639180f37',
    messagingSenderId: '1072582012438',
    projectId: 'smartclass-ef1bf',
    storageBucket: 'smartclass-ef1bf.firebasestorage.app',
    iosBundleId: 'com.smartclass.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3kWHk7R2dcclIwWQBbRohYjnRiY1PHYs',
    appId: '1:1072582012438:web:f18bcc47e41b83df180f37',
    messagingSenderId: '1072582012438',
    projectId: 'smartclass-ef1bf',
    authDomain: 'smartclass-ef1bf.firebaseapp.com',
    storageBucket: 'smartclass-ef1bf.firebasestorage.app',
    measurementId: 'G-86K3TV35YP',
  );
}
